'use client';

import { createContext, useContext, useEffect, useState } from 'react';

export const TEXTOS: Record<string, any> = {
  es: {
    bienvenido: 'Bienvenido de nuevo,', misPts: 'Mis pts', posicion: 'Posición', referidos: 'REFERIDOS',
    mundialTitulo: 'PRODE MUNDIAL 2026', mundialSub: 'Lanzamiento: 1 May 2026 · El más completo',
    crearGrupo: 'CREAR GRUPO', crearGrupoSub: 'Jugá con tus amigos · Elegí la liga',
    prodeComunitario: 'PRODE COMUNITARIO', prodeComunitarioSub: 'Todos contra todos · Elegí la liga',
    ligasDisponibles: 'Ligas disponibles', proximamente: 'Próximamente',
    descargar: 'DESCARGAR PICKGOL', descargarSub: 'Instalá la app en tu celular · Gratis',
    inicio: 'Inicio', fixture: 'Fixture', grupos: 'Grupos', jugadas: 'Jugadas', perfil: 'Perfil',
    invitarAmigos: 'Invitar amigos', referidosSub: 'Invitá amigos y ganá jugadas gratis para el Mundial',
    totalReferidos: 'Referidos', jugadasGratis: 'Jugadas gratis', proximoNivel: 'Próximo nivel',
    tuLink: 'Tu link de invitación', copiar: 'Copiar', invitar: 'INVITAR AMIGOS', recompensas: 'Recompensas',
    ganado: '¡Ganado!', faltan: 'Faltán', paraGanar: 'referidos para ganar',
    miPerfil: 'Mi Perfil', nombreUsuario: 'Nombre de usuario', editar: 'Editar',
    guardar: 'GUARDAR', cancelar: 'CANCELAR', idioma: 'Idioma', infoCuenta: 'Información de cuenta',
    cerrarSesion: 'CERRAR SESIÓN', sinNombre: 'Sin nombre configurado',
    plus: 'PICKGOL PLUS', plusSub: 'Personalizá tu experiencia al máximo',
    activarPlus: 'ACTIVAR PLUS', yaEsPlus: '¡Ya sos Plus!',
    yaEsPlusSub: 'Tenés acceso a todas las funciones premium',
    procesado: 'Pago seguro con PayPal · Pago único',
    terminos: 'Términos · Privacidad · Reembolsos',
    metodoPago: 'Método de acceso',
    misJugadasSub: 'Todas tus jugadas activas',
    noJugadas: 'No tenés jugadas todavía',
    noJugadasSub: 'Entrá a un grupo y creá tu primera jugada',
    irGrupos: 'IR A MIS GRUPOS',
    sinGrupo: 'Sin grupo',
    pagadoConfirmado: '✅ Pago confirmado',
    pagoPendiente: '⏳ Pago pendiente',
    cargandoJugadas: 'Cargando jugadas...',
    tuMejorJugada: 'Tu mejor jugada',
    misGruposSub: 'Todos tus grupos activos',
    noGrupos: 'No tenés grupos todavía',
    noGruposSub: 'Creá un grupo o unite con un código',
    creador: 'Creador',
    jugadores: 'jugadores',
    cargandoGrupos: 'Cargando grupos...',
    unirme: '🔗 UNIRME',
    fixtureTitulo: 'Fixture',
    cargandoPartidos: 'Cargando partidos...',
    noPartidos: 'No hay partidos disponibles',
    proxLiga: 'El fixture de esta liga estará disponible pronto',
    fin: 'FIN',
    crearGrupoTitulo: 'Crear Grupo',
    crearGrupoGratis: 'Gratis · Lanzamiento PickGol 2026',
    nombreGrupo: 'Nombre del grupo',
    ligaLabel: 'Liga',
    duracion: 'Duración del torneo',
    todaTemporada: '📅 Toda la temporada',
    fechasEspecificas: '🎯 Fechas específicas',
    variablesGrupo: 'Variables del grupo',
    predeterminadas: '✅ Predeterminadas',
    lasDefinoYo: '✏️ Las defino yo',
    variablesStandard: 'Se usarán las variables estándar de PickGol con sus puntos originales.',
    variablesPersonalizadas: 'Variables personalizadas',
    activarPlus2: 'Activá PickGol Plus para crear tus propias variables',
    controlPagos: 'Control de pagos internos',
    controlPagosSub: 'Activá para gestionar quién pagó en tu grupo',
    precioInterno: 'Precio interno por jugada (opcional)',
    precioSub: 'Monto que cada jugador te paga a vos por fuera de la app. PickGol no lo gestiona.',
    chatGrupo: 'Chat del grupo',
    chatGrupoSub: 'Habilitá el chat para que los jugadores puedan hablar',
    infoGratis: 'Crear el grupo es gratis. Aprovechá el lanzamiento de PickGol 2026 — ningún jugador paga a PickGol al crear sus jugadas.',
    creando: 'CREANDO...',
    sinControlTitulo: 'Sin control de pagos',
    sinControlDesc: 'Va a crear el grupo sin control de pagos internos. Los jugadores no tendrán seguimiento de pagos. ¿Desea continuar?',
    siContinuar: 'SÍ, CONTINUAR SIN CONTROL',
    configurarPagos: 'CONFIGURAR PAGOS',
    unirseGrupo: 'Unirse a un grupo',
    unirseDesc: 'Ingresá el código que te compartió el creador',
    codigoGrupo: 'Código del grupo',
    buscarGrupo: 'BUSCAR GRUPO',
    buscando: 'BUSCANDO...',
    uniendose: 'UNIÉNDOSE...',
    unirmeBtn: '✅ UNIRME A ESTE GRUPO',
    grupoCosto: 'Grupo con costo',
    grupoCostoDesc: 'Este grupo tiene un costo interno de',
    grupoCostoDesc2: 'por jugada, a pagar por fuera de la app al creador del grupo.',
    siUnirme: 'SÍ, UNIRME AL GRUPO',
    todaLaTemporada: 'Toda la temporada',
    fechasEsp: 'Fechas específicas',
    miembro: 'miembro',
    miembros: 'miembros',
    codigoIncorrecto: 'Código incorrecto. Verificá e intentá de nuevo.',
    errorBuscar: 'Error al buscar el grupo. Intentá de nuevo.',
    errorUnirse: 'Error al unirse al grupo. Intentá de nuevo.',
    ingresaCodigo: 'Ingresá un código de grupo',
  },
  pt: {
    bienvenido: 'Bem-vindo de volta,', misPts: 'Meus pts', posicion: 'Posição', referidos: 'INDICADOS',
    mundialTitulo: 'PRODE COPA DO MUNDO 2026', mundialSub: 'Lançamento: 1 Mai 2026 · O mais completo',
    crearGrupo: 'CRIAR GRUPO', crearGrupoSub: 'Jogue com seus amigos · Escolha a liga',
    prodeComunitario: 'PRODE COMUNITÁRIO', prodeComunitarioSub: 'Todos contra todos · Escolha a liga',
    ligasDisponibles: 'Ligas disponíveis', proximamente: 'Em breve',
    descargar: 'BAIXAR PICKGOL', descargarSub: 'Instale o app no seu celular · Grátis',
    inicio: 'Início', fixture: 'Jogos', grupos: 'Grupos', jugadas: 'Apostas', perfil: 'Perfil',
    invitarAmigos: 'Convidar amigos', referidosSub: 'Indique amigos e ganhe apostas grátis para a Copa',
    totalReferidos: 'Indicados', jugadasGratis: 'Apostas grátis', proximoNivel: 'Próximo nível',
    tuLink: 'Seu link de convite', copiar: 'Copiar', invitar: 'CONVIDAR AMIGOS', recompensas: 'Recompensas',
    ganado: 'Conquistado!', faltan: 'Faltam', paraGanar: 'indicados para ganhar',
    miPerfil: 'Meu Perfil', nombreUsuario: 'Nome de usuário', editar: 'Editar',
    guardar: 'SALVAR', cancelar: 'CANCELAR', idioma: 'Idioma', infoCuenta: 'Informações da conta',
    cerrarSesion: 'SAIR', sinNombre: 'Sem nome configurado',
    plus: 'PICKGOL PLUS', plusSub: 'Personalize sua experiência ao máximo',
    activarPlus: 'ATIVAR PLUS', yaEsPlus: 'Você já é Plus!',
    yaEsPlusSub: 'Você tem acesso a todas as funções premium',
    procesado: 'Pagamento seguro com PayPal · Pagamento único',
    terminos: 'Termos · Privacidade · Reembolsos',
    metodoPago: 'Método de acesso',
    misJugadasSub: 'Todas as suas apostas ativas',
    noJugadas: 'Você não tem apostas ainda',
    noJugadasSub: 'Entre em um grupo e crie sua primeira aposta',
    irGrupos: 'IR PARA MEUS GRUPOS',
    sinGrupo: 'Sem grupo',
    pagadoConfirmado: '✅ Pagamento confirmado',
    pagoPendiente: '⏳ Pagamento pendente',
    cargandoJugadas: 'Carregando apostas...',
    tuMejorJugada: 'Sua melhor aposta',
    misGruposSub: 'Todos os seus grupos ativos',
    noGrupos: 'Você não tem grupos ainda',
    noGruposSub: 'Crie um grupo ou entre com um código',
    creador: 'Criador',
    jugadores: 'jogadores',
    cargandoGrupos: 'Carregando grupos...',
    unirme: '🔗 ENTRAR',
    fixtureTitulo: 'Jogos',
    cargandoPartidos: 'Carregando jogos...',
    noPartidos: 'Nenhum jogo disponível',
    proxLiga: 'O fixture desta liga estará disponível em breve',
    fin: 'FIM',
    crearGrupoTitulo: 'Criar Grupo',
    crearGrupoGratis: 'Grátis · Lançamento PickGol 2026',
    nombreGrupo: 'Nome do grupo',
    ligaLabel: 'Liga',
    duracion: 'Duração do torneio',
    todaTemporada: '📅 Toda a temporada',
    fechasEspecificas: '🎯 Datas específicas',
    variablesGrupo: 'Variáveis do grupo',
    predeterminadas: '✅ Predefinidas',
    lasDefinoYo: '✏️ Eu defino',
    variablesStandard: 'Serão usadas as variáveis padrão do PickGol com sua pontuação original.',
    variablesPersonalizadas: 'Variáveis personalizadas',
    activarPlus2: 'Ative o PickGol Plus para criar suas próprias variáveis',
    controlPagos: 'Controle de pagamentos internos',
    controlPagosSub: 'Ative para gerenciar quem pagou no seu grupo',
    precioInterno: 'Preço interno por aposta (opcional)',
    precioSub: 'Valor que cada jogador paga para você fora do app. PickGol não gerencia.',
    chatGrupo: 'Chat do grupo',
    chatGrupoSub: 'Habilite o chat para que os jogadores possam conversar',
    infoGratis: 'Criar o grupo é grátis. Aproveite o lançamento do PickGol 2026 — nenhum jogador paga ao PickGol ao criar suas apostas.',
    creando: 'CRIANDO...',
    sinControlTitulo: 'Sem controle de pagamentos',
    sinControlDesc: 'Vai criar o grupo sem controle de pagamentos internos. Os jogadores não terão acompanhamento de pagamentos. Deseja continuar?',
    siContinuar: 'SIM, CONTINUAR SEM CONTROLE',
    configurarPagos: 'CONFIGURAR PAGAMENTOS',
    unirseGrupo: 'Entrar em um grupo',
    unirseDesc: 'Digite o código que o criador compartilhou com você',
    codigoGrupo: 'Código do grupo',
    buscarGrupo: 'BUSCAR GRUPO',
    buscando: 'BUSCANDO...',
    uniendose: 'ENTRANDO...',
    unirmeBtn: '✅ ENTRAR NESTE GRUPO',
    grupoCosto: 'Grupo com custo',
    grupoCostoDesc: 'Este grupo tem um custo interno de',
    grupoCostoDesc2: 'por aposta, a pagar fora do app ao criador do grupo.',
    siUnirme: 'SIM, ENTRAR NO GRUPO',
    todaLaTemporada: 'Toda a temporada',
    fechasEsp: 'Datas específicas',
    miembro: 'membro',
    miembros: 'membros',
    codigoIncorrecto: 'Código incorreto. Verifique e tente novamente.',
    errorBuscar: 'Erro ao buscar o grupo. Tente novamente.',
    errorUnirse: 'Erro ao entrar no grupo. Tente novamente.',
    ingresaCodigo: 'Digite um código de grupo',
  },
  en: {
    bienvenido: 'Welcome back,', misPts: 'My pts', posicion: 'Position', referidos: 'REFERRALS',
    mundialTitulo: 'WORLD CUP 2026 PREDICTIONS', mundialSub: 'Launch: May 1, 2026 · The most complete',
    crearGrupo: 'CREATE GROUP', crearGrupoSub: 'Play with your friends · Choose a league',
    prodeComunitario: 'COMMUNITY PREDICTIONS', prodeComunitarioSub: 'Everyone vs everyone · Choose a league',
    ligasDisponibles: 'Available leagues', proximamente: 'Coming soon',
    descargar: 'DOWNLOAD PICKGOL', descargarSub: 'Install the app on your phone · Free',
    inicio: 'Home', fixture: 'Fixture', grupos: 'Groups', jugadas: 'Predictions', perfil: 'Profile',
    invitarAmigos: 'Invite friends', referidosSub: 'Invite friends and earn free predictions for the World Cup',
    totalReferidos: 'Referrals', jugadasGratis: 'Free predictions', proximoNivel: 'Next level',
    tuLink: 'Your invite link', copiar: 'Copy', invitar: 'INVITE FRIENDS', recompensas: 'Rewards',
    ganado: 'Earned!', faltan: 'You need', paraGanar: 'more referrals to earn',
    miPerfil: 'My Profile', nombreUsuario: 'Username', editar: 'Edit',
    guardar: 'SAVE', cancelar: 'CANCEL', idioma: 'Language', infoCuenta: 'Account information',
    cerrarSesion: 'SIGN OUT', sinNombre: 'No name configured',
    plus: 'PICKGOL PLUS', plusSub: 'Customize your experience to the fullest',
    activarPlus: 'ACTIVATE PLUS', yaEsPlus: "You're already Plus!",
    yaEsPlusSub: 'You have access to all premium features',
    procesado: 'Secure payment with PayPal · One-time payment',
    terminos: 'Terms · Privacy · Refunds',
    metodoPago: 'Access method',
    misJugadasSub: 'All your active predictions',
    noJugadas: "You don't have predictions yet",
    noJugadasSub: 'Join a group and create your first prediction',
    irGrupos: 'GO TO MY GROUPS',
    sinGrupo: 'No group',
    pagadoConfirmado: '✅ Payment confirmed',
    pagoPendiente: '⏳ Payment pending',
    cargandoJugadas: 'Loading predictions...',
    tuMejorJugada: 'Your best prediction',
    misGruposSub: 'All your active groups',
    noGrupos: "You don't have groups yet",
    noGruposSub: 'Create a group or join with a code',
    creador: 'Creator',
    jugadores: 'players',
    cargandoGrupos: 'Loading groups...',
    unirme: '🔗 JOIN',
    fixtureTitulo: 'Fixture',
    cargandoPartidos: 'Loading matches...',
    noPartidos: 'No matches available',
    proxLiga: 'This league fixture will be available soon',
    fin: 'END',
    crearGrupoTitulo: 'Create Group',
    crearGrupoGratis: 'Free · PickGol 2026 Launch',
    nombreGrupo: 'Group name',
    ligaLabel: 'League',
    duracion: 'Tournament duration',
    todaTemporada: '📅 Full season',
    fechasEspecificas: '🎯 Specific dates',
    variablesGrupo: 'Group variables',
    predeterminadas: '✅ Default',
    lasDefinoYo: '✏️ I define them',
    variablesStandard: 'Standard PickGol variables will be used with their original scores.',
    variablesPersonalizadas: 'Custom variables',
    activarPlus2: 'Activate PickGol Plus to create your own variables',
    controlPagos: 'Internal payment control',
    controlPagosSub: 'Enable to track who has paid in your group',
    precioInterno: 'Internal price per prediction (optional)',
    precioSub: 'Amount each player pays you outside the app. PickGol does not manage this.',
    chatGrupo: 'Group chat',
    chatGrupoSub: 'Enable chat so players can talk',
    infoGratis: 'Creating a group is free. Take advantage of the PickGol 2026 launch — no player pays PickGol when creating predictions.',
    creando: 'CREATING...',
    sinControlTitulo: 'No payment control',
    sinControlDesc: 'You will create the group without internal payment control. Players will not have payment tracking. Do you want to continue?',
    siContinuar: 'YES, CONTINUE WITHOUT CONTROL',
    configurarPagos: 'SET UP PAYMENTS',
    unirseGrupo: 'Join a group',
    unirseDesc: 'Enter the code shared by the group creator',
    codigoGrupo: 'Group code',
    buscarGrupo: 'SEARCH GROUP',
    buscando: 'SEARCHING...',
    uniendose: 'JOINING...',
    unirmeBtn: '✅ JOIN THIS GROUP',
    grupoCosto: 'Group with cost',
    grupoCostoDesc: 'This group has an internal cost of',
    grupoCostoDesc2: 'per prediction, to be paid outside the app to the group creator.',
    siUnirme: 'YES, JOIN THE GROUP',
    todaLaTemporada: 'Full season',
    fechasEsp: 'Specific dates',
    miembro: 'member',
    miembros: 'members',
    codigoIncorrecto: 'Incorrect code. Please verify and try again.',
    errorBuscar: 'Error searching for group. Please try again.',
    errorUnirse: 'Error joining group. Please try again.',
    ingresaCodigo: 'Enter a group code',
  },
};

const IdiomaContext = createContext<{
  locale: string;
  t: Record<string, string>;
  setLocale: (l: string) => void;
  ready: boolean;
}>({
  locale: 'es',
  t: TEXTOS.es,
  setLocale: () => {},
  ready: false,
});

export function IdiomaProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState('es');
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('pickgol_idioma');
    if (saved && TEXTOS[saved]) setLocaleState(saved);
    setReady(true);
  }, []);

  const setLocale = (l: string) => {
    setLocaleState(l);
    localStorage.setItem('pickgol_idioma', l);
  };

  return (
    <IdiomaContext.Provider value={{ locale, t: TEXTOS[locale] || TEXTOS.es, setLocale, ready }}>
      {children}
    </IdiomaContext.Provider>
  );
}

export function useIdioma() {
  return useContext(IdiomaContext);
}
